// Thin indirection over the Wails v3 bindings + @wailsio/runtime so that the
// rest of the React app does not need to know the exact path to the
// auto-generated bindings or the runtime event-bus shape.
//
// The bindings directory is regenerated by `wails3 generate bindings -ts -d
// frontend/bindings`. If you change a Go method signature, regenerate before
// rebuilding the frontend.

import { Events } from '@wailsio/runtime';

import * as App from '../bindings/burp-upstream-adapter/app';
import type {
  CheckResult,
  ConfigDTO,
  LogEntry,
  MetricsSnapshot,
  ProfileSummary,
} from './types';

// Re-export the bound Go methods. We unwrap the CancellablePromise return
// type into a plain Promise so call sites can keep using `.then(...)` /
// `await`. Cancellation isn't needed for any of these RPCs in practice.
export const GetConfig = (): Promise<ConfigDTO> =>
  App.GetConfig() as unknown as Promise<ConfigDTO>;
export const SaveConfig = (dto: ConfigDTO): Promise<void> =>
  App.SaveConfig(dto as any) as unknown as Promise<void>;
export const StartProxy = () => App.StartProxy() as unknown as Promise<void>;
export const StopProxy = () => App.StopProxy() as unknown as Promise<void>;
export const GetStatus = () => App.GetStatus() as unknown as Promise<string>;
export const GetMetrics = () => App.GetMetrics() as unknown as Promise<MetricsSnapshot>;
export const GetLogs = () => App.GetLogs() as unknown as Promise<LogEntry[]>;
export const ClearLogs = () => App.ClearLogs() as unknown as Promise<void>;
export const LoadCAPEMFromFile = () =>
  App.LoadCAPEMFromFile() as unknown as Promise<string>;

export const ListProfiles = () => App.ListProfiles() as unknown as Promise<ProfileSummary[]>;
export const SwitchProfile = (name: string) =>
  App.SwitchProfile(name) as unknown as Promise<ConfigDTO>;
export const CreateProfile = (name: string) =>
  App.CreateProfile(name) as unknown as Promise<ConfigDTO>;
export const DuplicateProfile = (src: string, dst: string) =>
  App.DuplicateProfile(src, dst) as unknown as Promise<ConfigDTO>;
export const RenameProfile = (oldName: string, newName: string) =>
  App.RenameProfile(oldName, newName) as unknown as Promise<ConfigDTO>;
export const DeleteProfile = (name: string) =>
  App.DeleteProfile(name) as unknown as Promise<ConfigDTO>;

export const TestUpstreamTLS = () => App.TestUpstreamTLS() as unknown as Promise<CheckResult>;
export const TestProxyAuth = () => App.TestProxyAuth() as unknown as Promise<CheckResult>;
export const TestCONNECT = (target: string) =>
  App.TestCONNECT(target) as unknown as Promise<CheckResult>;
export const TestHTTPGet = (url: string) =>
  App.TestHTTPGet(url) as unknown as Promise<CheckResult>;

// Event bridge. Wails v3 returns a cleanup function from `Events.On`, but the
// existing component subscribes once and tears down via a separate `EventsOff`
// call. We adapt the v3 contract by tracking the cleanups per event name.
const eventCleanups = new Map<string, (() => void)[]>();

export function EventsOn<T = any>(eventName: string, callback: (data: T) => void): void {
  const cleanup = Events.On(eventName, (e) => callback(e.data as T));
  const list = eventCleanups.get(eventName) ?? [];
  list.push(cleanup);
  eventCleanups.set(eventName, list);
}

export function EventsOff(eventName: string): void {
  const list = eventCleanups.get(eventName);
  if (!list) return;
  for (const cleanup of list) cleanup();
  eventCleanups.delete(eventName);
}
