// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectCAFile() {
  return window['go']['main']['App']['SelectCAFile']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestCONNECT(arg1) {
  return window['go']['main']['App']['TestCONNECT'](arg1);
}

export function TestHTTPGet(arg1) {
  return window['go']['main']['App']['TestHTTPGet'](arg1);
}

export function TestProxyAuth() {
  return window['go']['main']['App']['TestProxyAuth']();
}

export function TestUpstreamTLS() {
  return window['go']['main']['App']['TestUpstreamTLS']();
}
