// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1, arg2) {
  return window['go']['main']['App']['DuplicateProfile'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadCAPEMFromFile() {
  return window['go']['main']['App']['LoadCAPEMFromFile']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function TestCONNECT(arg1) {
  return window['go']['main']['App']['TestCONNECT'](arg1);
}

export function TestHTTPGet(arg1) {
  return window['go']['main']['App']['TestHTTPGet'](arg1);
}

export function TestProxyAuth() {
  return window['go']['main']['App']['TestProxyAuth']();
}

export function TestUpstreamTLS() {
  return window['go']['main']['App']['TestUpstreamTLS']();
}
